Sprint 3/step 1
marovdm/react-burger pull request #5
Opened 2023-02-08 18:21 UTC by marovdm

2023-02-08 18:39 UTC, marovdm commented
Не совсем разобрался, откуда мы должны получать пароль пользователя для формы на странице профиля? В ответе он не приходит, локально его не храним. Мне кажется это плохая практика хранить его где бы то ни было в незашифрованном виде. Может что-то упустил, прошу разъяснить этот момент.

2023-02-08 20:30 UTC, andryxxa93 requested changes
Отличная работа!
Что понравилось:
- Реализован механизм обновления протухшего токена
- Реализован скролл по категориям
- Настроены все необходимые редиректы после авторизационных действий 

Что необходимо исправить:
- Не работает восстановление пароля. Ендпоинт не верный. 
![Снимок экрана 2023-02-08 в 23 26 06](https://user-images.githubusercontent.com/60173362/217643335-cdcd26f7-ce0e-4ea4-b02a-b4124cba708d.png)


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачи!

P.S. насчет вашего вопроса о пароле. Вы совершенно верно подметили, что пароль хранить и получать откуда-то небезопасно. В форме его не нужно подставлять, во-первых это сделает сам браузер, если инпут имеет тип `password` и во-вторых в этом нет никакой необходимости потому что пароль не отображается в явном виде, а "зашифрован" точками.

2023-02-08 20:30 UTC, andryxxa93 commented on src/models/forgot-password/forgot-password.jsx
> +        navigate('/reset-password', {state: 'reset'});
**Можно лучше**
Хорошей практикой считается хранить роуты в константах - так сложнее ошибиться и удобнее их менять.

2023-02-08 20:30 UTC, andryxxa93 commented on src/models/register/register.jsx
> +  useEffect(() => {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-02-09 15:17 UTC, marovdm commented
Спасибо за ответ! Сделал работу над ошибками по комментариям. За изначально некорректный url сброса пароля извиняюсь, тестировал ошибку)

2023-02-09 16:46 UTC, andryxxa93 approved these changes
Да, теперь всё отлично! Работа принята, удачного вам продолжения обучения!

2023-02-19 10:59 UTC, merged